/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      container: {
        center: true,
        padding: '2rem',
        screens: {
          '2xl': '1400px',
        },
      },
      colors: {
        'p-bg': 'var(--p-color-bg)',
        'p-bg-inverse': 'var(--p-color-bg-inverse)',
        'p-bg-surface': 'var(--p-color-bg-surface)',
        'p-bg-surface-hover': 'var(--p-color-bg-surface-hover)',
        'p-bg-surface-active': 'var(--p-color-bg-surface-active)',
        'p-bg-surface-selected': 'var(--p-color-bg-surface-selected)',
        'p-bg-surface-disabled': 'var(--p-color-bg-surface-disabled)',
        'p-bg-surface-secondary': 'var(--p-color-bg-surface-secondary)',
        'p-bg-surface-info': 'var(--p-color-bg-surface-info)',
        'p-bg-surface-success': 'var(--p-color-bg-surface-success)',
        'p-bg-surface-caution': 'var(--p-color-bg-surface-caution)',
        'p-text': 'var(--p-color-text)',
        'p-text-secondary': 'var(--p-color-text-secondary)',
        'p-text-disabled': 'var(--p-color-text-disabled)',
        'p-text-inverse': 'var(--p-color-text-inverse)',
        'p-text-info': 'var(--p-color-text-info)',
        'p-text-success': 'var(--p-color-text-success)',
        'p-text-caution': 'var(--p-color-text-caution)',
        'p-text-critical': 'var(--p-color-text-critical)',
        'p-border': 'var(--p-color-border)',
        'p-border-secondary': 'var(--p-color-border-secondary)',
        'p-border-info': 'var(--p-color-border-info)',
        'p-border-success': 'var(--p-color-border-success)',
        'p-border-caution': 'var(--p-color-border-caution)',
        'p-border-critical': 'var(--p-color-border-critical)',
        'p-icon': 'var(--p-color-icon)',
        'p-icon-secondary': 'var(--p-color-icon-secondary)',
        'p-icon-disabled': 'var(--p-color-icon-disabled)',
        'p-icon-info': 'var(--p-color-icon-info)',
        'p-icon-success': 'var(--p-color-icon-success)',
        'p-icon-caution': 'var(--p-color-icon-caution)',
        'p-icon-critical': 'var(--p-color-icon-critical)',
      },
      spacing: {
        'p-space-0': 'var(--p-space-0)',
        'p-space-025': 'var(--p-space-025)',
        'p-space-050': 'var(--p-space-050)',
        'p-space-075': 'var(--p-space-075)',
        'p-space-100': 'var(--p-space-100)',
        'p-space-150': 'var(--p-space-150)',
        'p-space-200': 'var(--p-space-200)',
        'p-space-250': 'var(--p-space-250)',
        'p-space-300': 'var(--p-space-300)',
        'p-space-350': 'var(--p-space-350)',
        'p-space-400': 'var(--p-space-400)',
        'p-space-450': 'var(--p-space-450)',
        'p-space-500': 'var(--p-space-500)',
        'p-space-550': 'var(--p-space-550)',
        'p-space-600': 'var(--p-space-600)',
        'p-space-650': 'var(--p-space-650)',
        'p-space-700': 'var(--p-space-700)',
        'p-space-750': 'var(--p-space-750)',
        'p-space-800': 'var(--p-space-800)',
        'p-space-900': 'var(--p-space-900)',
        'p-space-1000': 'var(--p-space-1000)',
        'p-space-1200': 'var(--p-space-1200)',
        'p-space-1400': 'var(--p-space-1400)',
        'p-space-1600': 'var(--p-space-1600)',
        'p-space-2000': 'var(--p-space-2000)',
        'p-space-2400': 'var(--p-space-2400)',
        'p-space-2800': 'var(--p-space-2800)',
        'p-space-3200': 'var(--p-space-3200)',
        'p-space-3600': 'var(--p-space-3600)',
        'p-space-4000': 'var(--p-space-4000)',
      },
    },
  },
  plugins: [],
};
