import type { MetadataRoute } from "next";
import { SITE_CONFIG } from "@/lib/constants";

export default function robots(): MetadataRoute.Robots {
	return {
		rules: [
			{
				userAgent: "*",
				allow: [
					"/",
					"/collections/all/",
					"/collections/",
					"/search",
					"/about",
					"/contact",
					"/faq",
					"/help",
					"/size-guide",
					"/care-instructions",
					"/shipping-delivery",
					"/returns-exchange",
					"/refund-policy",
					"/privacy-policy",
					"/terms-of-service",
					"/cookie-policy",
					"/accessibility-statement",
					"/blog/",
					"/news/",
					"/press",
					"/careers",
					"/api/feed/google-merchant",
				],
				disallow: [
					"/account/",
					"/cart",
					"/checkout/",
					"/admin/",
					"/api/",
					"/_next/",
					"/static/",
					"/offline",
					"/404",
					"/500",
					"*.json",
					"*.xml$",
					"/share",
					"/upload",
				],
				crawlDelay: 1,
			},
			{
				userAgent: "Googlebot",
				allow: [
					"/",
					"/collections/all/",
					"/collections/",
					"/search",
					"/about",
					"/contact",
					"/api/feed/google-merchant",
				],
				disallow: [
					"/account/",
					"/cart",
					"/checkout/",
					"/admin/",
					"/api/",
					"/_next/",
					"/static/",
				],
				crawlDelay: 0.5,
			},
			{
				userAgent: "Bingbot",
				allow: [
					"/",
					"/collections/all/",
					"/collections/",
					"/search",
					"/about",
					"/contact",
				],
				disallow: [
					"/account/",
					"/cart",
					"/checkout/",
					"/admin/",
					"/api/",
					"/_next/",
					"/static/",
				],
				crawlDelay: 1,
			},
			{
				userAgent: "facebookexternalhit",
				allow: ["/", "/collections/all/", "/collections/"],
				disallow: ["/account/", "/cart", "/checkout/", "/admin/", "/api/"],
			},
			{
				userAgent: "Twitterbot",
				allow: ["/", "/collections/all/", "/collections/"],
				disallow: ["/account/", "/cart", "/checkout/", "/admin/", "/api/"],
			},
		],
		sitemap: `${SITE_CONFIG.url}/sitemap-index.xml`,
		host: SITE_CONFIG.url,
	};
}