export interface Country {
  name: string;
  code: string;
  emoji: string;
  callingCode: string;
  format: string;
}

export const countries: Country[] = [
  {
    name: "United States",
    code: "US",
    emoji: "🇺🇸",
    callingCode: "+1",
    format: "(###) ###-####",
  },
  {
    name: "Canada",
    code: "CA",
    emoji: "🇨🇦",
    callingCode: "+1",
    format: "(###) ###-####",
  },
  {
    name: "United Kingdom",
    code: "GB",
    emoji: "🇬🇧",
    callingCode: "+44",
    format: "#### ######",
  },
  {
    name: "Australia",
    code: "AU",
    emoji: "🇦🇺",
    callingCode: "+61",
    format: "#### ####",
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "🇩🇪",
    callingCode: "+49",
    format: "### #######",
  },
  {
    name: "France",
    code: "FR",
    emoji: "🇫🇷",
    callingCode: "+33",
    format: "# ## ## ## ##",
  },
  {
    name: "Spain",
    code: "ES",
    emoji: "🇪🇸",
    callingCode: "+34",
    format: "### ### ###",
  },
  {
    name: "Italy",
    code: "IT",
    emoji: "🇮🇹",
    callingCode: "+39",
    format: "### ### ####",
  },
  {
    name: "Netherlands",
    code: "NL",
    emoji: "🇳🇱",
    callingCode: "+31",
    format: "## ### ####",
  },
  {
    name: "Belgium",
    code: "BE",
    emoji: "🇧🇪",
    callingCode: "+32",
    format: "### ## ## ##",
  },
  {
    name: "Switzerland",
    code: "CH",
    emoji: "🇨🇭",
    callingCode: "+41",
    format: "## ### ## ##",
  },
  {
    name: "Austria",
    code: "AT",
    emoji: "🇦🇹",
    callingCode: "+43",
    format: "### ### ####",
  },
  {
    name: "Sweden",
    code: "SE",
    emoji: "🇸🇪",
    callingCode: "+46",
    format: "##-### ## ##",
  },
  {
    name: "Norway",
    code: "NO",
    emoji: "🇳🇴",
    callingCode: "+47",
    format: "### ## ###",
  },
  {
    name: "Denmark",
    code: "DK",
    emoji: "🇩🇰",
    callingCode: "+45",
    format: "## ## ## ##",
  },
  {
    name: "Finland",
    code: "FI",
    emoji: "🇫🇮",
    callingCode: "+358",
    format: "## ### ####",
  },
  {
    name: "Japan",
    code: "JP",
    emoji: "🇯🇵",
    callingCode: "+81",
    format: "##-####-####",
  },
  {
    name: "South Korea",
    code: "KR",
    emoji: "🇰🇷",
    callingCode: "+82",
    format: "##-####-####",
  },
  {
    name: "China",
    code: "CN",
    emoji: "🇨🇳",
    callingCode: "+86",
    format: "### #### ####",
  },
  {
    name: "Hong Kong",
    code: "HK",
    emoji: "��",
    callingCode: "+852",
    format: "#### ####",
  },
  {
    name: "Singapore",
    code: "SG",
    emoji: "🇸🇬",
    callingCode: "+65",
    format: "#### ####",
  },
  {
    name: "India",
    code: "IN",
    emoji: "🇮🇳",
    callingCode: "+91",
    format: "#### ######",
  },
  {
    name: "Brazil",
    code: "BR",
    emoji: "🇧🇷",
    callingCode: "+55",
    format: "(##) #####-####",
  },
  {
    name: "Mexico",
    code: "MX",
    emoji: "🇲🇽",
    callingCode: "+52",
    format: "(##) ####-####",
  },
  {
    name: "Argentina",
    code: "AR",
    emoji: "🇦🇷",
    callingCode: "+54",
    format: "(##) ####-####",
  },
  {
    name: "Chile",
    code: "CL",
    emoji: "🇨🇱",
    callingCode: "+56",
    format: "# #### ####",
  },
  {
    name: "Colombia",
    code: "CO",
    emoji: "🇨�",
    callingCode: "+57",
    format: "### ### ####",
  },
  {
    name: "South Africa",
    code: "ZA",
    emoji: "🇿🇦",
    callingCode: "+27",
    format: "## ### ####",
  },
  {
    name: "Nigeria",
    code: "NG",
    emoji: "🇳🇬",
    callingCode: "+234",
    format: "### ### ####",
  },
  {
    name: "Egypt",
    code: "EG",
    emoji: "🇪🇬",
    callingCode: "+20",
    format: "## #### ####",
  },
  {
    name: "Israel",
    code: "IL",
    emoji: "🇮🇱",
    callingCode: "+972",
    format: "##-###-####",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    emoji: "🇦🇪",
    callingCode: "+971",
    format: "## ### ####",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    emoji: "🇸🇦",
    callingCode: "+966",
    format: "## ### ####",
  },
  {
    name: "New Zealand",
    code: "NZ",
    emoji: "🇳🇿",
    callingCode: "+64",
    format: "## ### ####",
  },
  {
    name: "Indonesia",
    code: "ID",
    emoji: "🇮🇩",
    callingCode: "+62",
    format: "###-###-####",
  },
  {
    name: "Malaysia",
    code: "MY",
    emoji: "🇲🇾",
    callingCode: "+60",
    format: "##-### ####",
  },
  {
    name: "Thailand",
    code: "TH",
    emoji: "🇹🇭",
    callingCode: "+66",
    format: "## ### ####",
  },
  {
    name: "Vietnam",
    code: "VN",
    emoji: "🇻🇳",
    callingCode: "+84",
    format: "## #### ####",
  },
  {
    name: "Philippines",
    code: "PH",
    emoji: "🇵🇭",
    callingCode: "+63",
    format: "### ### ####",
  },
  {
    name: "Turkey",
    code: "TR",
    emoji: "🇹🇷",
    callingCode: "+90",
    format: "(###) ### ####",
  },
  {
    name: "Russia",
    code: "RU",
    emoji: "🇷🇺",
    callingCode: "+7",
    format: "(###) ###-##-##",
  },
  {
    name: "Poland",
    code: "PL",
    emoji: "🇵🇱",
    callingCode: "+48",
    format: "### ### ###",
  },
  {
    name: "Ukraine",
    code: "UA",
    emoji: "🇺🇦",
    callingCode: "+380",
    format: "## ### ####",
  },
];
